### PR TITLE
M1 Mac Improvements

### LINKED ISSUE #59: `cachesize()` and `cachelinesize()` throw `BoundsError` on M1 Mac
As reported by @plessl over at #58, on an M1 Mac one gets

```julia
julia> cachesize()
┌ Warning: Not all L1 cache sizes are equal. Consider using `l1cache_sizes()` instead.
└ @ Hwloc ~/.julia/packages/Hwloc/HorQV/src/highlevel_api.jl:201
┌ Warning: Not all L2 cache sizes are equal. Consider using `l2cache_sizes()` instead.
└ @ Hwloc ~/.julia/packages/Hwloc/HorQV/src/highlevel_api.jl:202
ERROR: BoundsError: attempt to access 0-element Vector{Any} at index [1]
Stacktrace:
  [1] getindex
    @ ./array.jl:924 [inlined]
  [2] first(a::Vector{Any})
    @ Base ./abstractarray.jl:404
  [3] cachesize()
    @ Hwloc ~/.julia/packages/Hwloc/HorQV/src/highlevel_api.jl:205
  [4] top-level scope
    @ REPL[6]:1
  [5] eval_user_input(ast::Any, backend::REPL.REPLBackend)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [6] repl_backend_loop(backend::REPL.REPLBackend)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [7] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [8] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [9] run_repl(repl::REPL.AbstractREPL, consumer::Any)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
 [10] (::Base.var"#967#969"{Bool, Bool, Bool})(REPL::Module)
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
 [11] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
 [12] exec_options(opts::Base.JLOptions)
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
 [13] _start()
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1

julia> cachelinesize()
ERROR: BoundsError: attempt to access 0-element Vector{Any} at index [1]
Stacktrace:
  [1] getindex
    @ ./array.jl:924 [inlined]
  [2] first(a::Vector{Any})
    @ Base ./abstractarray.jl:404
  [3] cachelinesize()
    @ Hwloc ~/.julia/packages/Hwloc/HorQV/src/highlevel_api.jl:222
  [4] top-level scope
    @ REPL[7]:1
  [5] eval_user_input(ast::Any, backend::REPL.REPLBackend)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [6] repl_backend_loop(backend::REPL.REPLBackend)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [7] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [8] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [9] run_repl(repl::REPL.AbstractREPL, consumer::Any)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
 [10] (::Base.var"#967#969"{Bool, Bool, Bool})(REPL::Module)
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
 [11] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
 [12] exec_options(opts::Base.JLOptions)
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
 [13] _start()
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
```

This is a bug since the documentation says: `Produces a warning if caches of the same level have different sizes across the system.`. So, to align with this documentation, I think we should throw warnings (they're missing for `cachelinesize`) and just return the first value.

### PR DESCRIPTION
**Pull request by carstenbauer**
Closes #59 and #60.

### CODE REVIEW

**Comment by carstenbauer** [comment]
With this PR on an M1 Mac:
```julia
julia> topology()
Machine (3.49 GB)
    Package L#0 P#0 (3.49 GB)
        NUMANode (3.49 GB)
        L2 (4.0 MB)
            L1 (64.0 kB) + I1 (128.0 kB)
                Core L#0 P#0
                    PU L#0 P#0
            L1 (64.0 kB) + I1 (128.0 kB)
                Core L#1 P#1
                    PU L#1 P#1
            L1 (64.0 kB) + I1 (128.0 kB)
                Core L#2 P#2
                    PU L#2 P#2
            L1 (64.0 kB) + I1 (128.0 kB)
                Core L#3 P#3
                    PU L#3 P#3
        L2 (12.0 MB)
            L1 (128.0 kB) + I1 (192.0 kB)
                Core L#4 P#4
                    PU L#4 P#4
            L1 (128.0 kB) + I1 (192.0 kB)
                Core L#5 P#5
                    PU L#5 P#5
            L1 (128.0 kB) + I1 (192.0 kB)
                Core L#6 P#6
                    PU L#6 P#6
            L1 (128.0 kB) + I1 (192.0 kB)
                Core L#7 P#7
                    PU L#7 P#7
```

```julia
julia> cachesize()
ERROR: Your system doesn't seem to have an L3 cache.
Stacktrace:
  [1] cachesize()
    @ Hwloc ~/repos/Hwloc.jl/src/highlevel_api.jl:205
  [2] top-level scope
    @ REPL[3]:1
  [3] eval_user_input(ast::Any, backend::REPL.REPLBackend)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [4] repl_backend_loop(backend::REPL.REPLBackend)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [5] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [6] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [7] run_repl(repl::REPL.AbstractREPL, consumer::Any)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [8] (::Base.var"#967#969"{Bool, Bool, Bool})(REPL::Module)
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [9] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
 [10] exec_options(opts::Base.JLOptions)
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
 [11] _start()
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1

julia> cachesize(:L1)
┌ Warning: Not all L1 cache sizes are equal.
└ @ Hwloc ~/repos/Hwloc.jl/src/highlevel_api.jl:231
65536

julia> cachesize(:L2)
┌ Warning: Not all L2 cache sizes are equal.
└ @ Hwloc ~/repos/Hwloc.jl/src/highlevel_api.jl:231
4194304
```

```julia
julia> cachelinesize()
ERROR: Your system doesn't seem to have an L3 cache.
Stacktrace:
  [1] cachelinesize()
    @ Hwloc ~/repos/Hwloc.jl/src/highlevel_api.jl:247
  [2] top-level scope
    @ REPL[6]:1
  [3] eval_user_input(ast::Any, backend::REPL.REPLBackend)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [4] repl_backend_loop(backend::REPL.REPLBackend)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [5] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [6] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [7] run_repl(repl::REPL.AbstractREPL, consumer::Any)
    @ REPL ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [8] (::Base.var"#967#969"{Bool, Bool, Bool})(REPL::Module)
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
  [9] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
 [10] exec_options(opts::Base.JLOptions)
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1
 [11] _start()
    @ Base ~/.julia/sysimgs/std_1.8_aarch64.so:-1

julia> cachelinesize(:L1)
128

julia> cachelinesize(:L2)
128
```

(cc @plessl)

**Comment by carstenbauer** [comment]
CI fails on x86 systems but only for Julia >= 1.7. This can't possibly be related to my PR. Since it fails with
```
This CPU does not provide information on cpuid leaf 0x00000004.
```
I suspect that this is, perhaps, an issue in CpuId.jl. Unfortunately, they only test x64 systems with [their CI.](https://travis-ci.org/github/m-j-w/CpuId.jl)

@m-j-w Do you have an idea what's going on here? Could it be related to [this commit](https://github.com/m-j-w/CpuId.jl/commit/b7c592e79dc5050e19a8c0ed73d04d7107fa3d89)?

File: src/highlevel_api.jl [hunk 1]
```diff
@@ -164,47 +164,74 @@ num_numa_nodes() = count(hwloc_isa(:NUMANode), gettopology())
...
 
+    isempty(l1) && throw(ErrorException("Your system doesn't seem to have an L1 cache."))
+    isempty(l2) && throw(ErrorException("Your system doesn't seem to have an L2 cache."))
+    isempty(l3) && throw(ErrorException("Your system doesn't seem to have an L3 cache."))
+
     allequal(l1) || (@warn "Not all L1 cache sizes are equal. Consider using `l1cache_sizes()` instead.")
     allequal(l2) || (@warn "Not all L2 cache sizes are equal. Consider using `l2cache_sizes()` instead.")
     allequal(l3) || (@warn "Not all L3 cache sizes are equal. Consider using `l3cache_sizes()` instead.")
 
     return (L1=first(l1), L2=first(l2), L3=first(l3))
```
Comment (plessl) [inline src/highlevel_api.jl]: Suggestion: To provide a defined behavior, I would rather return the largest caches size for each level. Because, on big.LITTLE type architectures, Julia tasks/threads will most likely run on the big cores. Picking first, leaves it to chance, which size is returned.

Comment (carstenbauer) [reply src/highlevel_api.jl]: It's not really random (given that hwloc is deterministic) but I'm fine with defaulting to the largest. Since we haven't documented what happens in such a case it's a non-breaking change.

File: .github/workflows/CI.yml [hunk 2]
```diff
@@ -10,8 +10,8 @@ jobs:
       fail-fast: false
       matrix:
         version:
-          - '1.3'
           - '1.6'
+          - '1.7'
```
Comment (eschnett) [inline .github/workflows/CI.yml:14]: Let's add `1.8-beta4` as well, that should become important soon.

File: src/highlevel_api.jl [hunk 3]
```diff
@@ -16,35 +16,35 @@ end
 
 Prints the topology of the given `obj` as a tree to `io`.
 """
-function print_topology(io::IO = stdout, obj::Object = gettopology(); indent = "", newline = false, prefix = "")
+function print_topology(io::IO=stdout, obj::Object=gettopology(); indent="", newline=false, prefix="")
```
Comment (eschnett) [inline src/highlevel_api.jl]: This PR has a lot of formatting changes.

Could you open a separate PR that only applies your formatting changes? (I assume you used an automatic tool for this.) This could be quickly merged, and then your real changes are better visible here.

File: src/highlevel_api.jl [hunk 4]
```diff
@@ -164,45 +164,72 @@ num_numa_nodes() = count(hwloc_isa(:NUMANode), gettopology())
...
     allequal(l2) || (@warn "Not all L2 cache sizes are equal. Consider using `l2cache_sizes()` instead.")
     allequal(l3) || (@warn "Not all L3 cache sizes are equal. Consider using `l3cache_sizes()` instead.")
 
-    return (L1=first(l1), L2=first(l2), L3=first(l3))
+    return (L1=maximum(l1), L2=maximum(l2), L3=maximum(l3))
+end
+
+"""
+    cachesize(x::Symbol) -> size
+Returns the size of the specified cache type. Allowed inputs are `:L1`, `:L2`, and `:L3`.
```
Comment (eschnett) [inline src/highlevel_api.jl:216]: Why is `:I1` not allowed? Isn't that introduced earlier?

Why use `:L1` instead of `:L1Cache` here? Isn't `:L1Cache` used above?

File: .github/workflows/CI.yml (hunk 2 above)
Comment (eschnett) [reply .github/workflows/CI.yml:14]: Sorry, that should be `1.8.0-rc4` instead.

**Comment by m-j-w** [comment]
> @m-j-w Do you have an idea what's going on here? Could it be related to [this commit](https://github.com/m-j-w/CpuId.jl/commit/b7c592e79dc5050e19a8c0ed73d04d7107fa3d89)?

The function throws in CpuId.jl 3.1 if the hardware is not compatible. Do you have the means to dump the data shown by the `cpuinfo()` function on that machine? Are you running the code on an actual Intel or AMD cpu?

I've created a separate [issue ](https://github.com/m-j-w/CpuId.jl/issues/55) on this on CpuId.jl for further discussion.

File: src/highlevel_api.jl (hunk 3 above)
Comment (carstenbauer) [reply src/highlevel_api.jl]: Argh, VS Code did this by itself. Will try to undo.

File: src/highlevel_api.jl (hunk 4 above)
Comment (carstenbauer) [reply src/highlevel_api.jl:216]: > Why is `:I1` not allowed? Isn't that introduced earlier?

I introduced `cachesize` (and `cachelinesize`) as high-level functions for grabbing information about common caches. It's never going to be "general" because a system could have whatever other caches (e.g., perhaps, an L4 cache) and we're always only supporting a finite list. The user can always fall back to querying the size manually (by iterating the topology tree) or by investigating the output of `topology()` of course. So, we could add `:I1` but it's an instruction cache and IMO typically not of great importance. What do you think?



> Why use `:L1` instead of `:L1Cache` here? Isn't `:L1Cache` used above?

The hwloc objects in the topology are called `:L1Cache`, yes. But I aligned it with the output of `cachesize()` (without arguments) which returns, e.g., `(L1 = 32768, L2 = 1048576, L3 = 28835840)` which is arguably nicer than `(L1Cache = 32768, L2Cache = 1048576, L3Cache = 28835840)`. Also, `:L1` is probably more intuitive than `:L1Cache`. But I don't have a strong opinion here.

File: .github/workflows/CI.yml (hunk 2 above)
Comment (carstenbauer) [reply .github/workflows/CI.yml:14]: Done.

File: src/highlevel_api.jl (hunk 3 above)
Comment (carstenbauer) [reply src/highlevel_api.jl]: Done.

File: src/highlevel_api.jl (hunk 4 above)
Comment (eschnett) [reply src/highlevel_api.jl:216]: Ok.

Comment (eschnett) [reply src/highlevel_api.jl:216]: Ok.

File: .github/workflows/CI.yml [hunk 5]
```diff
@@ -10,8 +10,9 @@ jobs:
...
+          - '1.8.0-rc4'
```
Comment (eschnett) [inline .github/workflows/CI.yml]: ... and now, `1.8` has been released!

**Comment by carstenbauer** [comment]
Note to self: Finish this :)

* [x] CI -> 1.8 stable
* [x] Drop/replace CpuId-based tests (because they fail on GitHub runners due to the issue mentioned above).

File: .github/workflows/CI.yml (hunk 5 above)
Comment (carstenbauer) [reply .github/workflows/CI.yml]: Done.

**Comment by carstenbauer** [comment]
@eschnett, FYI, conditional on successful CI runs I plan to merge this later today.

Any objections to tagging a new minor release afterwards? (I can take care of it)
